### ISSUE TITLE
Serious question: Why isn't this more popular?

### ISSUE THREAD

**Issue by Nautman** [codecoolture/next-joi#8]
Hi,

I am just learning how to develop with nextjs and am planning to use API routes. Like with any API, I understand there needs to be some validation.

To my great surprise, I can hardly find any information on how to validate nextjs API routes. I had believed it would be a much more common use case. The closest information is your package, and it has around 300 downloads this week; a number I thought would be higher.

Therefore, I am wondering if you can help me understand how most people validate their nextjs API routes? Also, is the lack of information due to the fact that people *aren't* using nextjs API routes?

Thank you for any help.

**Comment by sergioalvz** [comment]
Hi, @Nautman:

Sadly, I think I don't have an answer to your question... But based on what I see out there, these are some ideas that may help us understand:

1) People rather verify requests deep into their business logic instead of at the "API route" level
2) People use NEXT.js to build front-end apps, and API routes are merely proxies for their back-ends (deployed elsewhere)
3) People are simply not verifying anything...

Glad you find the package interesting, though! :-)

**Comment by sergioalvz** [comment]
I've opened a pull request in vercel/next.js#25759 weeks ago, but it hasn't been either reviewed or merged. I might help to spread the package.
